/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DAO.NhanVienDAO;
import DAO.TaiKhoanDAO;
import Helper.DateHelper;
import Helper.MsgBox;
import Helper.XImage;
import Model.NhanVien;
import Model.TaiKhoan;
import java.awt.Frame;
import java.text.ParseException;
import java.text.ParsePosition;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.activation.DataHandler;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class nhanvien extends javax.swing.JPanel {

    /**
     * Creates new form JPkhachHang
     */
    int index = 0;
    NhanVienDAO nvd = new NhanVienDAO();
    TaiKhoanDAO tkd = new TaiKhoanDAO();

    public nhanvien() {

        initComponents();
        init();

    }
    private static final SimpleDateFormat sdf = new SimpleDateFormat("dd-mm-yyyy");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tab = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        btnmoi = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnFisrt = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txthoten = new javax.swing.JTextField();
        txtngaysinh = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtsdt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtmanv = new javax.swing.JTextField();
        txtcccd = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdiachi = new javax.swing.JTextArea();
        rdonu = new javax.swing.JRadioButton();
        rdonam = new javax.swing.JRadioButton();
        txttentk = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtmk = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblnhanvien = new javax.swing.JTable();
        tbltk = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 204));

        tab.setBackground(new java.awt.Color(255, 255, 255));
        tab.setForeground(new java.awt.Color(0, 51, 0));
        tab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        btnmoi.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnmoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add-icon.png"))); // NOI18N
        btnmoi.setText("Mới");
        btnmoi.setFocusPainted(false);
        btnmoi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnmoi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmoiActionPerformed(evt);
            }
        });

        btnInsert.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Plus-icon.png"))); // NOI18N
        btnInsert.setText("Thêm");
        btnInsert.setFocusPainted(false);
        btnInsert.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInsert.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Minu-icon.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.setFocusPainted(false);
        btnDelete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh-icon.png"))); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.setFocusPainted(false);
        btnUpdate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnFisrt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/First-icon.png"))); // NOI18N
        btnFisrt.setFocusPainted(false);
        btnFisrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFisrtActionPerformed(evt);
            }
        });

        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pre-Music-icon.png"))); // NOI18N
        btnPrev.setFocusPainted(false);
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Next-Music-icon.png"))); // NOI18N
        btnNext.setFocusPainted(false);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Last-icon.png"))); // NOI18N
        btnLast.setFocusPainted(false);
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Mã NV");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("Họ và tên");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setText("CCCD");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setText("Giới tính");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setText("Địa chỉ");

        txthoten.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txthoten.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtngaysinh.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtngaysinh.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtemail.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtemail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        txtsdt.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtsdt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel8.setText("Email");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel9.setText("Số ĐT");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel10.setText("Ngày sinh");

        txtmanv.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtmanv.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtcccd.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtcccd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtcccd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcccdActionPerformed(evt);
            }
        });

        txtdiachi.setColumns(20);
        txtdiachi.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtdiachi.setRows(5);
        jScrollPane2.setViewportView(txtdiachi);

        rdonu.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(rdonu);
        rdonu.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        rdonu.setText("Nữ");
        rdonu.setFocusPainted(false);
        rdonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdonuActionPerformed(evt);
            }
        });

        rdonam.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(rdonam);
        rdonam.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        rdonam.setText("Nam");
        rdonam.setFocusPainted(false);
        rdonam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdonamActionPerformed(evt);
            }
        });

        txttentk.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txttentk.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txttentk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttentkActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel11.setText("Tên Tài Khoản");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel12.setText("Mật Khẩu");

        txtmk.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtmk.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcccd, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmanv, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rdonam)
                                .addGap(18, 18, 18)
                                .addComponent(rdonu))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnFisrt, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12))))
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txttentk, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtmk, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnmoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInsert)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtmanv, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtcccd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(rdonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rdonam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txttentk, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFisrt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPrev, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNext, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLast, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmk, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInsert)
                            .addComponent(btnmoi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete))))
                .addGap(48, 48, 48))
        );

        tab.addTab("Cập nhật thông tin", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        tblnhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Tên NV", "Tên Tài Khoản", "Giới Tính", "Địa Chỉ", "Ngày Sinh", "Email", "CCCD", "SDT"
            }
        ));
        tblnhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblnhanvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblnhanvien);

        tbltk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên Tài Khoản", "Mật Khẩu", "Vai Trò"
            }
        ));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                .addGap(9, 9, 9))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(tbltk, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addGap(0, 71, Short.MAX_VALUE)
                    .addComponent(tbltk, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        tab.addTab("Danh sách nhân viên", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtcccdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcccdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcccdActionPerformed

    private void rdonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdonuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdonuActionPerformed

    private void rdonamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdonamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdonamActionPerformed

    private void btnFisrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFisrtActionPerformed
        this.index = 0;
        this.edit();
    }//GEN-LAST:event_btnFisrtActionPerformed

    private void txttentkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttentkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttentkActionPerformed

    private void txtmkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmkActionPerformed

    private void tblnhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblnhanvienMouseClicked
        if (evt.getClickCount() == 2) {
            this.index = tblnhanvien.rowAtPoint(evt.getPoint());
            if (this.index >= 0) {
                this.edit();
                tab.setSelectedIndex(0);
                txtmanv.setEditable(false);
                txttentk.setEditable(false);
            }
        }
    }//GEN-LAST:event_tblnhanvienMouseClicked

    private void btnmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoiActionPerformed

        this.clear();
        txtmanv.setEditable(true);
        txttentk.setEditable(true);
    }//GEN-LAST:event_btnmoiActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        check();
        if (flag == true) {
            insert();
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            if (!isValid(txtngaysinh.getText())) {
                MsgBox.alert(this, "Bạn Phải Nhập Đúng Định Dạng dd-mm-yyyy");
            } else {
                this.update();
            }
        } catch (Exception e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        if (this.index == 0) {
            this.index = tblnhanvien.getRowCount() - 1;
            this.edit();
        } else {
            this.index--;
            this.edit();
        }

    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (this.index == tblnhanvien.getRowCount() - 1) {
            index = 0;
            edit();
        } else {
            this.index++;
            this.edit();
        }

    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        this.index = tblnhanvien.getRowCount() - 1;
        this.edit();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        this.delete();
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFisrt;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnmoi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdonam;
    private javax.swing.JRadioButton rdonu;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTable tblnhanvien;
    private javax.swing.JTable tbltk;
    private javax.swing.JTextField txtcccd;
    private javax.swing.JTextArea txtdiachi;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtmanv;
    private javax.swing.JTextField txtmk;
    private javax.swing.JTextField txtngaysinh;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txttentk;
    // End of variables declaration//GEN-END:variables

    private void init() {
//        setIconImage(XImage.APP_ICON);
        loadnv();
        loadtk();
        tblnhanvien.setDefaultEditor(Object.class, null);
        this.setStatus(true);
        btnInsert.setEnabled(false);
        buttonGroup1.clearSelection();

    }

    public static boolean isValid(final String date) {

        boolean valid = false;

        try {
            // why 2008-02-2x, 20-11-02, 12012-04-05 are valid date?
            sdf.parse(date);
            // strict mode - check 30 or 31 days, leap year
            sdf.setLenient(false);
            valid = true;

        } catch (ParseException e) {
            e.printStackTrace();
            valid = false;
        }

        return valid;
    }

    private void loadnv() {
        DefaultTableModel model = (DefaultTableModel) tblnhanvien.getModel();
        model.setRowCount(0);
        try {
            List<NhanVien> listnv = nvd.selectAll();
            for (NhanVien nv : listnv) {
                Object[] row = {
                    nv.getMaNV(),
                    nv.getTenNV(),
                    nv.getTenTK(),
                    nv.isGioiTinh() ? "Nữ" : "Nam",
                    nv.getDiaChi(),
                    DateHelper.toString(nv.getNgaySinh()),
                    nv.getEmail(),
                    nv.getCCCD(),
                    nv.getSoDienThoai(),};
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi Kiểm Tra Dữ Liệu!");
            System.out.println(e);
        }
    }

    private void loadtk() {
        DefaultTableModel model = (DefaultTableModel) tbltk.getModel();
        model.setRowCount(0);
        try {
            List<TaiKhoan> listtk = tkd.selectAll();
            for (TaiKhoan tk : listtk) {
                Object[] row = {
                    tk.getTenTK(),
                    tk.getMatKhau(),
                    tk.getVaiTro(),};
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi Kiểm Tra Dữ Liệu!");
            System.out.println(e);
        }
    }

    private void edit() {
        try {
            String manv = (String) tblnhanvien.getValueAt(this.index, 0);
            String tentk = (String) tblnhanvien.getValueAt(this.index, 2);
            NhanVien modelnv = nvd.selectById(manv);
            TaiKhoan modeltk = tkd.selectById(tentk);
            if (modelnv != null && modeltk != null) {
                this.setModel(modelnv, modeltk);
                this.setStatus(false);
            }

        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi");
            System.out.println(e);
        }
    }

    private void setStatus(boolean insertable) {
        btnInsert.setEnabled(insertable);
        btnUpdate.setEnabled(!insertable);
        btnDelete.setEnabled(!insertable);
        boolean first = this.index > 0;
        boolean last = this.index < tblnhanvien.getRowCount() - 1;
        btnFisrt.setEnabled(!insertable && first);
        btnPrev.setEnabled(!insertable && first);
        btnNext.setEnabled(!insertable && last);
        btnLast.setEnabled(!insertable && last);
    }

    private void setModel(NhanVien modelnv, TaiKhoan modeltk) {
        txtmanv.setText(modelnv.getMaNV());
        txthoten.setText(modelnv.getTenNV());
        txttentk.setText(modeltk.getTenTK());
        txtemail.setText(modelnv.getEmail());
        txtngaysinh.setText(DateHelper.toString(modelnv.getNgaySinh()));
        txtdiachi.setText(modelnv.getDiaChi());
        txtcccd.setText(modelnv.getCCCD());
        txtsdt.setText(modelnv.getSoDienThoai());
        String gt = modelnv.isGioiTinh() ? "Nữ" : "Nam";
        if (gt.equalsIgnoreCase("Nam")) {
            rdonam.setSelected(true);
        } else {
            rdonu.setSelected(true);
        }
        txtmk.setText(modeltk.getMatKhau());
    }

    private NhanVien getModelnv() {
        NhanVien model = new NhanVien();
        model.setMaNV(txtmanv.getText());
        model.setTenNV(txthoten.getText());
        model.setTenTK(txttentk.getText());
        model.setCCCD(txtcccd.getText());
        model.setDiaChi(txtdiachi.getText());
        model.setSoDienThoai(txtsdt.getText());
        model.setEmail(txtemail.getText());
        model.setNgaySinh(DateHelper.toDate(txtngaysinh.getText()));
        model.setGioiTinh(rdonu.isSelected());
        return model;
    }

    private TaiKhoan getModeltk() {
        TaiKhoan model = new TaiKhoan();
        model.setTenTK(txttentk.getText());
        model.setMatKhau(txtmk.getText());
        model.setVaiTro("Nhân Viên");

        return model;
    }

    private void insert() {
        NhanVien modelnv = getModelnv();
        TaiKhoan modeltk = getModeltk();
//        if (!isValidate(model)) {
//            return;
//        }
        try {
            tkd.insert(modeltk);
            nvd.insert(modelnv);

            this.loadtk();
            this.loadnv();

            this.clear();
            MsgBox.alert(this, "Thêm Nhân Viên Thành Công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm Nhân Viên Thất Bại!");
            System.out.println(e);
        }
    }

    private void update() {
        NhanVien modelnv = getModelnv();
        TaiKhoan modeltk = getModeltk();
        try {
            tkd.update(modeltk);
            nvd.update(modelnv);
            this.loadtk();
            this.loadnv();
            MsgBox.alert(this, "Cập Nhật Nhân Viên Thành Công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Cập Nhật Nhân Viên Thất Bại!");
            System.out.println(e);
        }
    }

    private void delete() {
//        if (!Auth.isManager()) {
//            msgbox.alert(this, "Bạn Không Có Quyền Xóa Chuyên Đề!");
//        } else 
        if (MsgBox.confirm(this, "Bạn Có Muốn Xóa Không?")) {

            String tk = txttentk.getText();
            try {

                nvd.deletenv_tk(tk);
                tkd.delete(tk);
                this.loadtk();
                this.loadnv();
                this.clear();

                MsgBox.alert(this, "Xóa Nhân Viên Thành Công!");
            } catch (Exception e) {
                MsgBox.alert(this, "Xóa Nhân Viên Thất Bại!");
                System.out.println(e);
            }
        }
    }

    private void clear() {
        this.setModel(new NhanVien(), new TaiKhoan());
        this.setStatus(true);
    }
    private static final String EMAIL_PATTERN
            = "/^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$/";

    public static boolean verifyEmail(String email) {
        if (email == null) {
            return false;
        }
        return email.matches(EMAIL_PATTERN);
    }
    boolean flag = false;

    void check() {

        List<NhanVien> listnv = nvd.selectAll();
        List<TaiKhoan> list = tkd.selectAll();
        for (NhanVien nv : listnv) {
            if (txtmanv.getText().equalsIgnoreCase(nv.getMaNV())) {
                MsgBox.alert(this, "Mã nhân viên đã tồn tại");
                System.out.println(nv.getMaNV());
                return;
            }
        }
        for (TaiKhoan nv : list) {
            if (txttentk.getText().equalsIgnoreCase(nv.getTenTK())) {
                MsgBox.alert(this, "Tên Tài Khoản Đã Tồn Tại");
                System.out.println(nv.getTenTK());
                return;
            }
        }

//        for(int )
//        String ma =  (String) tblnhanvien.getValueAt(index, 0);
        if (txtmanv.getText().length() == 0) {
            MsgBox.alert(this, "Mã nhân viên không được để trống");
        } else if (txthoten.getText().length() == 0) {
            MsgBox.alert(this, "Tên khách hàng không được để trống");
        } else if (txtcccd.getText().length() == 12) {
            MsgBox.alert(this, "Căn cứ công dân phải đủ 12 số");
        } else if (!rdonam.isSelected() && !rdonu.isSelected()) {
            MsgBox.alert(this, "Không được để trống giới tính");
        } else if (txtdiachi.getText().length() == 0) {
            MsgBox.alert(this, "Không được để trống địa chỉ");
        } else if (txtsdt.getText().length() < 10 || txtsdt.getText().length() > 11) {
            MsgBox.alert(this, "Số điện thoại phải nhập đủ 10 số");
        } else if (txtemail.getText().length() == 0) {
            MsgBox.alert(this, "Không được để trống email");
        } else if (verifyEmail(txtemail.getText())) {
            MsgBox.alert(this, "Email không đúng định dạng");
        } else if (txttentk.getText().length() == 0) {
            MsgBox.alert(this, "Không được để trống tên tài khoản");
        } else if (txtmk.getText().length() == 0) {
            MsgBox.alert(this, "Không được để trống tài khoản");
        } else if (txtmk.getText().length() < 1 || txtmk.getText().length() > 30) {
            MsgBox.alert(this, "Mật khẩu có độ dài từ 1 đến 30 ký tự");
        } else {
            flag = true;
        }
    }

}
