/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DAO.SanPhamDAO;
import javax.swing.JPanel;

/**
 *
 * @author vutai
 */
public class Showsanpham extends javax.swing.JPanel {

    private static JPanel initPanel;

    /**
     * Creates new form Showsanpham
     */
    public Showsanpham() {
        initComponents();

    }

    private void showpanel(JPanel panel) {
        initPanel = panel;
        slideshow1.removeAll();
        slideshow1.add(initPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        slideshow1 = new slideshow.Slideshow();
        jPanel1 = new javax.swing.JPanel();
        lblGia1 = new javax.swing.JLabel();
        lblTenSP1 = new javax.swing.JLabel();
        lblHinh1 = new javax.swing.JLabel();
        lblMaSP1 = new javax.swing.JLabel();
        lblTenSP4 = new javax.swing.JLabel();
        lblMaSP4 = new javax.swing.JLabel();
        lblGia4 = new javax.swing.JLabel();
        lblHinh4 = new javax.swing.JLabel();
        lblHinh2 = new javax.swing.JLabel();
        lblGia5 = new javax.swing.JLabel();
        lblTenSP5 = new javax.swing.JLabel();
        lblMaSP5 = new javax.swing.JLabel();
        lblGia2 = new javax.swing.JLabel();
        lblTenSP2 = new javax.swing.JLabel();
        lblMaSP2 = new javax.swing.JLabel();
        lblHinh5 = new javax.swing.JLabel();
        lblHinh6 = new javax.swing.JLabel();
        lblGia6 = new javax.swing.JLabel();
        lblTenSP6 = new javax.swing.JLabel();
        lblMaSP6 = new javax.swing.JLabel();
        lblHinh3 = new javax.swing.JLabel();
        lblGia3 = new javax.swing.JLabel();
        lblTenSP3 = new javax.swing.JLabel();
        lblMaSP3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setPreferredSize(new java.awt.Dimension(805, 471));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(slideshow1, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slideshow1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );

        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(805, 471));

        lblGia1.setText("200000");

        lblTenSP1.setText("Áo Thun Form Rộng");

        lblHinh1.setBackground(new java.awt.Color(255, 255, 255));
        lblHinh1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinh1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aoFormRong.jpg"))); // NOI18N
        lblHinh1.setText("Hình ảnh");
        lblHinh1.setOpaque(true);
        lblHinh1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblHinh1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        lblHinh1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinh1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHinh1MousePressed(evt);
            }
        });

        lblMaSP1.setText("SP01");

        lblTenSP4.setText("Sơ Mi tay Ngắn");

        lblMaSP4.setText("SP04");

        lblGia4.setText("180000");

        lblHinh4.setBackground(new java.awt.Color(255, 255, 255));
        lblHinh4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinh4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SoMiTayNgan.jpg"))); // NOI18N
        lblHinh4.setText("Hình ảnh");
        lblHinh4.setOpaque(true);
        lblHinh4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinh4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHinh4MousePressed(evt);
            }
        });

        lblHinh2.setBackground(new java.awt.Color(255, 255, 255));
        lblHinh2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinh2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aoThunTayLo.jpg"))); // NOI18N
        lblHinh2.setText("Hình ảnh");
        lblHinh2.setOpaque(true);
        lblHinh2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinh2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHinh2MousePressed(evt);
            }
        });

        lblGia5.setText("150000");

        lblTenSP5.setText("Áo Gió 2 Lớp");

        lblMaSP5.setText("SP05");

        lblGia2.setText("150000");

        lblTenSP2.setText("Áo Thun Tay Lở");

        lblMaSP2.setText("SP02");

        lblHinh5.setBackground(new java.awt.Color(255, 255, 255));
        lblHinh5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinh5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AoGio2Lop.jpg"))); // NOI18N
        lblHinh5.setText("Hình ảnh");
        lblHinh5.setOpaque(true);
        lblHinh5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinh5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHinh5MousePressed(evt);
            }
        });

        lblHinh6.setBackground(new java.awt.Color(255, 255, 255));
        lblHinh6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinh6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AoThunTheThao.jpg"))); // NOI18N
        lblHinh6.setText("Hình ảnh");
        lblHinh6.setOpaque(true);
        lblHinh6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinh6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHinh6MousePressed(evt);
            }
        });

        lblGia6.setText("100000");

        lblTenSP6.setText("Áo Thun Thể Thao");

        lblMaSP6.setText("SP06");

        lblHinh3.setBackground(new java.awt.Color(255, 255, 255));
        lblHinh3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinh3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hoodieTHEGOOD.jpg"))); // NOI18N
        lblHinh3.setText("Hình ảnh");
        lblHinh3.setOpaque(true);
        lblHinh3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinh3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHinh3MousePressed(evt);
            }
        });

        lblGia3.setText("250000");

        lblTenSP3.setText("Áo Hoodie The Good");

        lblMaSP3.setText("SP03");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblHinh1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaSP1)
                            .addComponent(lblTenSP1)
                            .addComponent(lblGia1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHinh2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaSP2)
                            .addComponent(lblTenSP2)
                            .addComponent(lblGia2))
                        .addGap(26, 26, 26)
                        .addComponent(lblHinh3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaSP3)
                            .addComponent(lblTenSP3)
                            .addComponent(lblGia3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblHinh4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaSP4)
                            .addComponent(lblGia4)
                            .addComponent(lblTenSP4))
                        .addGap(32, 32, 32)
                        .addComponent(lblHinh5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaSP5)
                            .addComponent(lblTenSP5)
                            .addComponent(lblGia5))
                        .addGap(38, 38, 38)
                        .addComponent(lblHinh6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaSP6)
                            .addComponent(lblTenSP6)
                            .addComponent(lblGia6))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblMaSP2)
                        .addGap(20, 20, 20)
                        .addComponent(lblTenSP2)
                        .addGap(20, 20, 20)
                        .addComponent(lblGia2))
                    .addComponent(lblHinh3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblHinh2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(lblHinh1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblMaSP3)
                            .addGap(20, 20, 20)
                            .addComponent(lblTenSP3)
                            .addGap(20, 20, 20)
                            .addComponent(lblGia3)
                            .addGap(26, 26, 26))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(lblMaSP1)
                            .addGap(20, 20, 20)
                            .addComponent(lblTenSP1)
                            .addGap(20, 20, 20)
                            .addComponent(lblGia1))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(lblMaSP5)
                        .addGap(20, 20, 20)
                        .addComponent(lblTenSP5)
                        .addGap(20, 20, 20)
                        .addComponent(lblGia5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHinh5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHinh6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lblHinh4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblMaSP4)
                                .addGap(20, 20, 20)
                                .addComponent(lblTenSP4)
                                .addGap(20, 20, 20)
                                .addComponent(lblGia4)
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblMaSP6)
                                .addGap(20, 20, 20)
                                .addComponent(lblTenSP6)
                                .addGap(20, 20, 20)
                                .addComponent(lblGia6)
                                .addGap(13, 13, 13)))))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblHinh1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinh1MouseClicked

    }//GEN-LAST:event_lblHinh1MouseClicked

    private void lblHinh1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblHinh1AncestorAdded

    }//GEN-LAST:event_lblHinh1AncestorAdded

    private void lblHinh1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinh1MousePressed
        showpanel(new ThongTinSP(lblMaSP1.getText()));
    }//GEN-LAST:event_lblHinh1MousePressed

    private void lblHinh2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinh2MouseClicked

    }//GEN-LAST:event_lblHinh2MouseClicked

    private void lblHinh3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinh3MouseClicked

    }//GEN-LAST:event_lblHinh3MouseClicked

    private void lblHinh4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinh4MouseClicked

    }//GEN-LAST:event_lblHinh4MouseClicked

    private void lblHinh5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinh5MouseClicked

    }//GEN-LAST:event_lblHinh5MouseClicked

    private void lblHinh6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinh6MouseClicked

    }//GEN-LAST:event_lblHinh6MouseClicked

    private void lblHinh2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinh2MousePressed
        showpanel(new ThongTinSP(lblMaSP2.getText()));
    }//GEN-LAST:event_lblHinh2MousePressed

    private void lblHinh3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinh3MousePressed
        showpanel(new ThongTinSP(lblMaSP3.getText()));
    }//GEN-LAST:event_lblHinh3MousePressed

    private void lblHinh4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinh4MousePressed
        showpanel(new ThongTinSP(lblMaSP4.getText()));
    }//GEN-LAST:event_lblHinh4MousePressed

    private void lblHinh5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinh5MousePressed
        showpanel(new ThongTinSP(lblMaSP5.getText()));
    }//GEN-LAST:event_lblHinh5MousePressed

    private void lblHinh6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinh6MousePressed
        showpanel(new ThongTinSP(lblMaSP6.getText()));
    }//GEN-LAST:event_lblHinh6MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblGia1;
    private javax.swing.JLabel lblGia2;
    private javax.swing.JLabel lblGia3;
    private javax.swing.JLabel lblGia4;
    private javax.swing.JLabel lblGia5;
    private javax.swing.JLabel lblGia6;
    private javax.swing.JLabel lblHinh1;
    private javax.swing.JLabel lblHinh2;
    private javax.swing.JLabel lblHinh3;
    private javax.swing.JLabel lblHinh4;
    private javax.swing.JLabel lblHinh5;
    private javax.swing.JLabel lblHinh6;
    private javax.swing.JLabel lblMaSP1;
    private javax.swing.JLabel lblMaSP2;
    private javax.swing.JLabel lblMaSP3;
    private javax.swing.JLabel lblMaSP4;
    private javax.swing.JLabel lblMaSP5;
    private javax.swing.JLabel lblMaSP6;
    private javax.swing.JLabel lblTenSP1;
    private javax.swing.JLabel lblTenSP2;
    private javax.swing.JLabel lblTenSP3;
    private javax.swing.JLabel lblTenSP4;
    private javax.swing.JLabel lblTenSP5;
    private javax.swing.JLabel lblTenSP6;
    private slideshow.Slideshow slideshow1;
    // End of variables declaration//GEN-END:variables
    

}
