/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DAO.ChiTietHoaDonXuatDAO;
import DAO.GioHangDAO;
import DAO.HoaDonXuatDAO;
import DAO.KhachHangDAO;
import DAO.SanPhamDAO;
import Helper.Auth;
import Helper.DateHelper;
import Helper.MsgBox;
import Helper.XImage;
import Model.ChiTietHoaDonXuat;
import Model.GioHang;
import Model.HoaDonXuat;
import Model.KhachHang;
import Model.NhanVien;
import Model.SanPham;
import Model.TaiKhoan;
import java.awt.Color;
import java.awt.Dimension;
import java.io.File;
import static java.lang.Integer.max;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Phan Tuan Kiet
 */
public class ThongTinSP extends javax.swing.JPanel {

    private static JPanel Panel;
    String maSP;
    int Mahdx;
    SanPhamDAO spd = new SanPhamDAO();
    GioHangDAO ghdao = new GioHangDAO();
    ChiTietHoaDonXuatDAO cthdxdao = new ChiTietHoaDonXuatDAO();
    HoaDonXuatDAO hdxdao = new HoaDonXuatDAO();
    KhachHangDAO khd = new KhachHangDAO();

    /**
     * Creates new form ThongTinSP
     */
    public ThongTinSP() {
        initComponents();
        setinfo();
    }

    public ThongTinSP(String maSP) {
        initComponents();
        this.maSP = maSP;
        setinfo();
    }

    private void showpanel(JPanel panel) {
        Panel = panel;
        slideshow1.removeAll();
        slideshow1.add(Panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        slideshow1 = new slideshow.Slideshow();
        jPanel1 = new javax.swing.JPanel();
        lblHinh = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblMaSP = new javax.swing.JLabel();
        lblTenSP = new javax.swing.JLabel();
        lblChatLieu = new javax.swing.JLabel();
        lblNguonGoc = new javax.swing.JLabel();
        lblSoLuong = new javax.swing.JLabel();
        lblKichCo = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGioiThieu = new javax.swing.JTextArea();
        btnInsert = new javax.swing.JButton();
        btnMua = new javax.swing.JButton();
        lblGiaBan = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        FileChooser = new javax.swing.JFileChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        spsoluong = new javax.swing.JTextField();

        jPasswordField1.setText("jPasswordField1");

        setPreferredSize(new java.awt.Dimension(650, 450));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slideshow1, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slideshow1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        lblHinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhMouseClicked(evt);
            }
        });

        jLabel1.setText("Mã Sản Phẩm :");

        jLabel2.setText("Tên Sản Phẩm :");

        jLabel3.setText("Chất Liệu :");

        jLabel4.setText("Nguồn Gốc :");

        jLabel5.setText("Số Lượng Còn Lại:");

        jLabel6.setText("Kích Cỡ :");

        lblMaSP.setText("jLabel7");

        lblTenSP.setText("jLabel7");

        lblChatLieu.setText("jLabel7");

        lblNguonGoc.setText("jLabel7");

        lblSoLuong.setText("jLabel7");

        lblKichCo.setText("jLabel7");

        jLabel13.setText("Giá Bán :");

        jLabel14.setText("Giới Thiệu Sản Phẩm");

        txtGioiThieu.setColumns(20);
        txtGioiThieu.setRows(5);
        jScrollPane1.setViewportView(txtGioiThieu);

        btnInsert.setText("Thêm Vào Giỏ Hàng");
        btnInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertMouseClicked(evt);
            }
        });
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnMua.setText("Mua Ngay");
        btnMua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuaActionPerformed(evt);
            }
        });

        lblGiaBan.setText("jLabel7");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Thông Tin Sản Phẩm");

        FileChooser.setDialogTitle("Chọn logo chuyên đề");

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.jpg"))); // NOI18N
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setText("Số Lượng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(lblGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnMua))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblKichCo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNguonGoc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 83, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(311, 311, 311)
                    .addComponent(FileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(394, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblMaSP))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblTenSP))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblChatLieu))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblNguonGoc))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblSoLuong))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblKichCo))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblGiaBan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMua, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(219, 219, 219)
                    .addComponent(FileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 11, Short.MAX_VALUE)
                    .addGap(220, 220, 220)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuaActionPerformed
        thanhToan tt = new thanhToan(null, true);
        tt.setVisible(true);
    }//GEN-LAST:event_btnMuaActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
//        showpanel(new GioHangUI());
//        btnInsert.hide();
//        btnMua.hide();
//        btnInsert.setBackground(Color.GRAY);
//        btnMua.setBackground(Color.GRAY);
        setmahdx();
        insert();
        SanPham sp = spd.selectById(maSP);
        sp = new SanPham();
        spd.updatesl(Integer.parseInt(lblSoLuong.getText()) - Integer.parseInt(spsoluong.getText()), maSP);
        setinfo();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void lblHinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhMouseClicked
//        this.selectImage();
    }//GEN-LAST:event_lblHinhMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        showpanel(new Showsanpham());
    }//GEN-LAST:event_jLabel7MouseClicked

    private void btnInsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertMouseClicked

    }//GEN-LAST:event_btnInsertMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnMua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChatLieu;
    private javax.swing.JLabel lblGiaBan;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblKichCo;
    private javax.swing.JLabel lblMaSP;
    private javax.swing.JLabel lblNguonGoc;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenSP;
    private slideshow.Slideshow slideshow1;
    private javax.swing.JTextField spsoluong;
    private javax.swing.JTextArea txtGioiThieu;
    // End of variables declaration//GEN-END:variables

    void selectImage() {
        if (FileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = FileChooser.getSelectedFile();
            if (XImage.saveLogo(file)) {
                ImageIcon icon = XImage.read(file.getName());
                lblHinh.setIcon(icon);
                lblHinh.setToolTipText(file.getName());
            }
        }
    }

    void setinfo() {
        SanPham sp = spd.selectById(maSP);

        try {
            float giaBan = sp.getGiaNhap() + ((sp.getGiaNhap() * 20 / 100));
            int giain = (int) giaBan;
            lblMaSP.setText(sp.getMaSP());
            lblTenSP.setText(sp.getTenSP());
            lblChatLieu.setText(sp.getChatLieu());
            lblNguonGoc.setText(sp.getNguocGoc());
            lblSoLuong.setText(String.valueOf(sp.getSoLuong()));
            lblKichCo.setText(sp.getKichCo());
            txtGioiThieu.setText(sp.getGioiThieu());
            lblGiaBan.setText(giain + "");
            if (sp.getHinh() != null) {
                lblHinh.setIcon(XImage.read(sp.getHinh()));
            }

        } catch (Exception e) {
        }
    }

    private void setmahdx() {

        List<HoaDonXuat> hdx = hdxdao.selectAll();
        int max = 0;
        for (int i = 0; i < hdx.size(); i++) {
            if (hdx.get(i).getMaHDX() > max) {
                max = hdx.get(i).getMaHDX();
            }
        }

        Mahdx = max + 1;

    }

    public boolean kiemtra() {
        SanPham sp = spd.selectById(maSP);
        try {
            if (spsoluong.getText().equalsIgnoreCase("")) {
                MsgBox.alert(this, "Bạn Chưa Chọn Số Lượng Sản Phẩm");
                return false;
            }
            if (Integer.valueOf(spsoluong.getText()) > sp.getSoLuong()) {
                MsgBox.alert(this, "Bạn Nhập Quá Số Lượng Sảm Phẩm Hiện Có");
                return false;
            }
        } catch (Exception e) {
        }

        return true;
    }

    private ChiTietHoaDonXuat getModecthdx() {
        ChiTietHoaDonXuat model = new ChiTietHoaDonXuat();
        model.setMaSP(lblMaSP.getText());
        model.setSoLuong(Integer.parseInt(spsoluong.getText()));
        model.setMaHDX(Mahdx);
        model.setGiaBan(Float.parseFloat(lblGiaBan.getText()));
        model.setTongTien(Float.parseFloat(lblGiaBan.getText()) * Integer.parseInt(spsoluong.getText()));
        return model;
    }

    private HoaDonXuat getModehdx() {
        KhachHang kh = khd.selecttkkhbyid(Auth.USER.getTenTK());
        HoaDonXuat model = new HoaDonXuat();
        model.setMaKH(kh.getMaKH());
        model.setMaNV("NV01");
        model.setMaHDX(Mahdx);
        model.setTinhTrang("Chờ Thanh Toán");
        model.setNgayBan(DateHelper.now());
        return model;
    }

    private void insert() {
        if (kiemtra()) {
            ChiTietHoaDonXuat modelcthd = getModecthdx();
            HoaDonXuat modelhd = getModehdx();
            try {
                hdxdao.insert(modelhd);
                cthdxdao.insert(modelcthd);
                MsgBox.alert(this, "Thêm Vào Giỏ Hàng Thành Công!");
            } catch (Exception e) {
                MsgBox.alert(this, "Thêm Vào Giỏ Hàng  Thất Bại!");
                System.out.println(e);
            }
        }
    }

}
