/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author ADMIN
 */
public class trangChu extends javax.swing.JFrame {

    private JPanel initPanel;

    /**
     * Creates new form trangChu
     */
    public trangChu() {
        initComponents();
        setLocationRelativeTo(null);
        init();
    }

    void init() {
        slideshowMain.initSlideshow(new Slide1(), new Slide2(), new Slide3(), new Slide4());
        ImageIcon icon = new ImageIcon("...\\icon\\cat-icon.png");
        setIconImage(icon.getImage());
        new Timer(1000, new ActionListener() {
            SimpleDateFormat format = new SimpleDateFormat("hh:mm:ss a");

            public void actionPerformed(ActionEvent e) {
                lbldongho.setText(format.format(new Date()));
            }
        }).start();

    }

    private void showpanel(JPanel panel) {
        initPanel = panel;
        slideshowMain.removeAll();
        slideshowMain.add(initPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pictureBox1 = new swing.PictureBox();
        jLabel1 = new javax.swing.JLabel();
        pnMain = new javax.swing.JPanel();
        slideshowMain = new slideshow.Slideshow();
        jPanel3 = new javax.swing.JPanel();
        btntrangchu = new javax.swing.JButton();
        btnsanpham = new javax.swing.JButton();
        btnkhachhang = new javax.swing.JButton();
        btnhoadon = new javax.swing.JButton();
        btnlogout = new swing.Buttont();
        lbldongho = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trang chủ - Quản lý");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("STZhongsong", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nhà OF Báo Fashion");

        slideshowMain.setBackground(new java.awt.Color(102, 102, 102));
        slideshowMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 771, Short.MAX_VALUE)
            .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(slideshowMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 765, Short.MAX_VALUE))
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(slideshowMain, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(null);

        btntrangchu.setBackground(new java.awt.Color(204, 204, 204));
        btntrangchu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btntrangchu.setForeground(new java.awt.Color(51, 51, 51));
        btntrangchu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home-icon.png"))); // NOI18N
        btntrangchu.setActionCommand("Trang chư");
        btntrangchu.setAlignmentX(5.0F);
        btntrangchu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        btntrangchu.setBorderPainted(false);
        btntrangchu.setContentAreaFilled(false);
        btntrangchu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btntrangchu.setDisabledSelectedIcon(null);
        btntrangchu.setFocusPainted(false);
        btntrangchu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btntrangchu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btntrangchu.setIconTextGap(5);
        btntrangchu.setInheritsPopupMenu(true);
        btntrangchu.setLabel("Trang chủ");
        btntrangchu.setMaximumSize(new java.awt.Dimension(275, 30));
        btntrangchu.setMinimumSize(new java.awt.Dimension(275, 30));
        btntrangchu.setRequestFocusEnabled(false);
        btntrangchu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntrangchuActionPerformed(evt);
            }
        });
        jPanel3.add(btntrangchu);
        btntrangchu.setBounds(0, 70, 240, 56);

        btnsanpham.setBackground(new java.awt.Color(204, 204, 204));
        btnsanpham.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnsanpham.setForeground(new java.awt.Color(51, 51, 51));
        btnsanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Product-icon.png"))); // NOI18N
        btnsanpham.setAlignmentX(5.0F);
        btnsanpham.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        btnsanpham.setBorderPainted(false);
        btnsanpham.setContentAreaFilled(false);
        btnsanpham.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnsanpham.setFocusPainted(false);
        btnsanpham.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnsanpham.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnsanpham.setIconTextGap(5);
        btnsanpham.setInheritsPopupMenu(true);
        btnsanpham.setLabel("Quản lý sản phẩm");
        btnsanpham.setMaximumSize(new java.awt.Dimension(275, 30));
        btnsanpham.setMinimumSize(new java.awt.Dimension(275, 30));
        btnsanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsanphamActionPerformed(evt);
            }
        });
        jPanel3.add(btnsanpham);
        btnsanpham.setBounds(0, 130, 240, 56);

        btnkhachhang.setBackground(new java.awt.Color(204, 204, 204));
        btnkhachhang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnkhachhang.setForeground(new java.awt.Color(51, 51, 51));
        btnkhachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/users-icon.png"))); // NOI18N
        btnkhachhang.setAlignmentX(5.0F);
        btnkhachhang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        btnkhachhang.setBorderPainted(false);
        btnkhachhang.setContentAreaFilled(false);
        btnkhachhang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnkhachhang.setFocusPainted(false);
        btnkhachhang.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnkhachhang.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnkhachhang.setIconTextGap(5);
        btnkhachhang.setInheritsPopupMenu(true);
        btnkhachhang.setLabel("Quản lý khách hàng");
        btnkhachhang.setMaximumSize(new java.awt.Dimension(275, 30));
        btnkhachhang.setMinimumSize(new java.awt.Dimension(275, 30));
        btnkhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhachhangActionPerformed(evt);
            }
        });
        jPanel3.add(btnkhachhang);
        btnkhachhang.setBounds(0, 190, 240, 56);

        btnhoadon.setBackground(new java.awt.Color(204, 204, 204));
        btnhoadon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnhoadon.setForeground(new java.awt.Color(51, 51, 51));
        btnhoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Bill-icon.png"))); // NOI18N
        btnhoadon.setAlignmentX(5.0F);
        btnhoadon.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        btnhoadon.setBorderPainted(false);
        btnhoadon.setContentAreaFilled(false);
        btnhoadon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnhoadon.setFocusPainted(false);
        btnhoadon.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnhoadon.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnhoadon.setIconTextGap(5);
        btnhoadon.setInheritsPopupMenu(true);
        btnhoadon.setLabel("Quản lý hóa đơn");
        btnhoadon.setMaximumSize(new java.awt.Dimension(275, 30));
        btnhoadon.setMinimumSize(new java.awt.Dimension(275, 30));
        btnhoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhoadonActionPerformed(evt);
            }
        });
        jPanel3.add(btnhoadon);
        btnhoadon.setBounds(0, 250, 240, 56);

        btnlogout.setBackground(new java.awt.Color(204, 204, 204));
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Logout-icon.png"))); // NOI18N
        btnlogout.setText("Đăng xuất");
        btnlogout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btntrangchuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btntrangchuMouseExited(evt);
            }
        });
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel3.add(btnlogout);
        btnlogout.setBounds(10, 510, 110, 35);

        lbldongho.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbldongho.setText("00:00:00");

        pictureBox1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pictureBox1.setLayer(pnMain, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pictureBox1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pictureBox1.setLayer(lbldongho, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pictureBox1Layout = new javax.swing.GroupLayout(pictureBox1);
        pictureBox1.setLayout(pictureBox1Layout);
        pictureBox1Layout.setHorizontalGroup(
            pictureBox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pictureBox1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pictureBox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pictureBox1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pictureBox1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbldongho)))
                .addContainerGap())
            .addGroup(pictureBox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pictureBox1Layout.createSequentialGroup()
                    .addContainerGap(253, Short.MAX_VALUE)
                    .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)))
        );
        pictureBox1Layout.setVerticalGroup(
            pictureBox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pictureBox1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 471, Short.MAX_VALUE)
                .addComponent(lbldongho)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pictureBox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pictureBox1Layout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(35, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pictureBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pictureBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsanphamActionPerformed
        btnhoadon.setContentAreaFilled(false);
        btntrangchu.setContentAreaFilled(false);

        btnkhachhang.setContentAreaFilled(false);

        btnsanpham.setContentAreaFilled(true);
        btnsanpham.setBackground(Color.GRAY);
        showpanel(new Sanpham());
    }//GEN-LAST:event_btnsanphamActionPerformed

    private void btnhoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhoadonActionPerformed
        btnkhachhang.setContentAreaFilled(false);
        btntrangchu.setContentAreaFilled(false);

        btnsanpham.setContentAreaFilled(false);

        btnhoadon.setContentAreaFilled(true);
        btnhoadon.setBackground(Color.GRAY);
        showpanel(new hoadon());
    }//GEN-LAST:event_btnhoadonActionPerformed

    private void btnkhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhachhangActionPerformed
        btnhoadon.setContentAreaFilled(false);
        btntrangchu.setContentAreaFilled(false);

        btnsanpham.setContentAreaFilled(false);

        btnkhachhang.setContentAreaFilled(true);
        btnkhachhang.setBackground(Color.GRAY);
        showpanel(new khachHang());
    }//GEN-LAST:event_btnkhachhangActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        this.dispose();
        DangNhap dn = new DangNhap();
        dn.setVisible(true);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btntrangchuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntrangchuMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btntrangchuMouseEntered

    private void btntrangchuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntrangchuMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btntrangchuMouseExited

    private void btntrangchuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntrangchuActionPerformed
//        slideshowMain.removeAll();
//        slideshowMain.initSlideshow(new Slide1(), new Slide2(), new Slide3(), new Slide4());
        showpanel(new SlideMain());
        btnkhachhang.setContentAreaFilled(false);
        btnhoadon.setContentAreaFilled(false);

        btnsanpham.setContentAreaFilled(false);

        btntrangchu.setContentAreaFilled(true);
        btntrangchu.setBackground(Color.GRAY);
    }//GEN-LAST:event_btntrangchuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhoadon;
    private javax.swing.JButton btnkhachhang;
    private swing.Buttont btnlogout;
    private javax.swing.JButton btnsanpham;
    private javax.swing.JButton btntrangchu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbldongho;
    private swing.PictureBox pictureBox1;
    private javax.swing.JPanel pnMain;
    private slideshow.Slideshow slideshowMain;
    // End of variables declaration//GEN-END:variables
}
