/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.KhachHangDAO;
import Helper.Auth;
import Model.KhachHang;
import Model.getssp;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author vutai
 */
public class TrangchuKH extends javax.swing.JFrame {

    KhachHangDAO khd = new KhachHangDAO();
    KhachHangDAO dao = new KhachHangDAO();
    private JPanel initPanel;
    int checkssp;

    /**
     * Creates new form TrangchuKH
     */
    public TrangchuKH() {
        initComponents();
        init();
        KhachHang kh = khd.selecttkkhbyid(Auth.USER.getTenTK());
        kh = dao.select(kh.getMaKH());
        lblhello.setText(kh.getTenKH());

    }

    void init() {

        this.setLocationRelativeTo(null);

        new Timer(1000, new ActionListener() {
            SimpleDateFormat format = new SimpleDateFormat("hh:mm:ss a");

            public void actionPerformed(ActionEvent e) {
                lbldongho.setText(format.format(new Date()));

            }
        }).start();
    }

    private void showpanel(JPanel panel) {
        initPanel = panel;
        slideshowMain.removeAll();
        slideshowMain.add(initPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pictureBox1 = new swing.PictureBox();
        jLabel1 = new javax.swing.JLabel();
        pnMain = new javax.swing.JPanel();
        slideshowMain = new slideshow.Slideshow();
        jPanel3 = new javax.swing.JPanel();
        btntrangchu = new javax.swing.JButton();
        btnthongtinkh = new javax.swing.JButton();
        btngiohang = new javax.swing.JButton();
        btnlogout = new swing.Buttont();
        jLabel2 = new javax.swing.JLabel();
        lblhello = new javax.swing.JLabel();
        lbldongho = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("STZhongsong", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nhà OF Báo Fashion");

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slideshowMain, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slideshowMain, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(null);

        btntrangchu.setBackground(new java.awt.Color(204, 204, 204));
        btntrangchu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btntrangchu.setForeground(new java.awt.Color(51, 51, 51));
        btntrangchu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home-icon.png"))); // NOI18N
        btntrangchu.setActionCommand("Trang chư");
        btntrangchu.setAlignmentX(5.0F);
        btntrangchu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        btntrangchu.setBorderPainted(false);
        btntrangchu.setContentAreaFilled(false);
        btntrangchu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btntrangchu.setDisabledSelectedIcon(null);
        btntrangchu.setFocusPainted(false);
        btntrangchu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btntrangchu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btntrangchu.setIconTextGap(5);
        btntrangchu.setInheritsPopupMenu(true);
        btntrangchu.setLabel("Trang chủ");
        btntrangchu.setMaximumSize(new java.awt.Dimension(275, 30));
        btntrangchu.setMinimumSize(new java.awt.Dimension(275, 30));
        btntrangchu.setRequestFocusEnabled(false);
        btntrangchu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntrangchuActionPerformed(evt);
            }
        });
        jPanel3.add(btntrangchu);
        btntrangchu.setBounds(0, 70, 240, 56);

        btnthongtinkh.setBackground(new java.awt.Color(204, 204, 204));
        btnthongtinkh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnthongtinkh.setForeground(new java.awt.Color(51, 51, 51));
        btnthongtinkh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/staff-icon.png"))); // NOI18N
        btnthongtinkh.setText("Thông Tin ");
        btnthongtinkh.setAlignmentX(5.0F);
        btnthongtinkh.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        btnthongtinkh.setBorderPainted(false);
        btnthongtinkh.setContentAreaFilled(false);
        btnthongtinkh.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnthongtinkh.setFocusPainted(false);
        btnthongtinkh.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnthongtinkh.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnthongtinkh.setIconTextGap(5);
        btnthongtinkh.setInheritsPopupMenu(true);
        btnthongtinkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthongtinkhActionPerformed(evt);
            }
        });
        jPanel3.add(btnthongtinkh);
        btnthongtinkh.setBounds(0, 120, 240, 56);

        btngiohang.setBackground(new java.awt.Color(204, 204, 204));
        btngiohang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btngiohang.setForeground(new java.awt.Color(51, 51, 51));
        btngiohang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Product-icon.png"))); // NOI18N
        btngiohang.setText("Giỏ Hàng");
        btngiohang.setAlignmentX(5.0F);
        btngiohang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        btngiohang.setBorderPainted(false);
        btngiohang.setContentAreaFilled(false);
        btngiohang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btngiohang.setFocusPainted(false);
        btngiohang.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btngiohang.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btngiohang.setIconTextGap(5);
        btngiohang.setInheritsPopupMenu(true);
        btngiohang.setMaximumSize(new java.awt.Dimension(275, 30));
        btngiohang.setMinimumSize(new java.awt.Dimension(275, 30));
        btngiohang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngiohangActionPerformed(evt);
            }
        });
        jPanel3.add(btngiohang);
        btngiohang.setBounds(0, 180, 240, 56);

        btnlogout.setBackground(new java.awt.Color(204, 204, 204));
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Logout-icon.png"))); // NOI18N
        btnlogout.setText("Đăng xuất");
        btnlogout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlogoutbtntrangchuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlogoutbtntrangchuMouseExited(evt);
            }
        });
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel3.add(btnlogout);
        btnlogout.setBounds(10, 510, 110, 35);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Chào");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 20, 40, 20);

        lblhello.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(lblhello);
        lblhello.setBounds(60, 20, 90, 20);

        lbldongho.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbldongho.setText("00:00:00");

        pictureBox1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pictureBox1.setLayer(pnMain, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pictureBox1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pictureBox1.setLayer(lbldongho, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pictureBox1Layout = new javax.swing.GroupLayout(pictureBox1);
        pictureBox1.setLayout(pictureBox1Layout);
        pictureBox1Layout.setHorizontalGroup(
            pictureBox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pictureBox1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pictureBox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pictureBox1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pictureBox1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbldongho)))
                .addContainerGap())
            .addGroup(pictureBox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pictureBox1Layout.createSequentialGroup()
                    .addContainerGap(253, Short.MAX_VALUE)
                    .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)))
        );
        pictureBox1Layout.setVerticalGroup(
            pictureBox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pictureBox1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 499, Short.MAX_VALUE)
                .addComponent(lbldongho)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pictureBox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pictureBox1Layout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(35, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pictureBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pictureBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntrangchuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntrangchuActionPerformed

        btnthongtinkh.setContentAreaFilled(false);
        btngiohang.setContentAreaFilled(false);
        btntrangchu.setContentAreaFilled(true);
        btntrangchu.setBackground(Color.GRAY);
        showpanel(new Showsanpham());
    }//GEN-LAST:event_btntrangchuActionPerformed

    private void btnthongtinkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthongtinkhActionPerformed

        btntrangchu.setContentAreaFilled(false);
        btngiohang.setContentAreaFilled(false);
        btnthongtinkh.setContentAreaFilled(true);
        btnthongtinkh.setBackground(Color.GRAY);
        showpanel(new thongtinkh());
    }//GEN-LAST:event_btnthongtinkhActionPerformed

    private void btngiohangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngiohangActionPerformed

        btntrangchu.setContentAreaFilled(false);
        btnthongtinkh.setContentAreaFilled(false);
        btngiohang.setContentAreaFilled(true);
        btngiohang.setBackground(Color.GRAY);
        showpanel(new GioHangUI());
    }//GEN-LAST:event_btngiohangActionPerformed

    private void btnlogoutbtntrangchuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutbtntrangchuMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlogoutbtntrangchuMouseEntered

    private void btnlogoutbtntrangchuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutbtntrangchuMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlogoutbtntrangchuMouseExited

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        this.dispose();
        DangNhap dn = new DangNhap();
        dn.setVisible(true);
        Auth.logoff();
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        showpanel(new Showsanpham());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangchuKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangchuKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangchuKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangchuKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangchuKH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngiohang;
    private swing.Buttont btnlogout;
    private javax.swing.JButton btnthongtinkh;
    private javax.swing.JButton btntrangchu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbldongho;
    private javax.swing.JLabel lblhello;
    private swing.PictureBox pictureBox1;
    private javax.swing.JPanel pnMain;
    private slideshow.Slideshow slideshowMain;
    // End of variables declaration//GEN-END:variables

}
